---
# 1. Nginx 배포 (Deployment 생성)
- name: Create Nginx Deployment
  shell: |
    kubectl apply -f - <<EOF
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment
      labels:
        app: nginx
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
        # [추가] control-plane 라벨이 없는 노드(Agent)에만 배포
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
            # [추가] 같은 노드에 Nginx Pod이 2개 이상 뜨지 못하게 강제 분산
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app: nginx
                topologyKey: "kubernetes.io/hostname"
          containers:
          - name: nginx
            image: nginx:latest
            ports:
            - containerPort: 80
    EOF
  delegate_to: "{{ groups['servers'][0] }}"

# 2. Nginx 서비스 (NodePort 설정)
- name: Create Nginx Service (NodePort)
  shell: |
    kubectl apply -f - <<EOF
    apiVersion: v1
    kind: Service
    metadata:
      name: nginx-service
    spec:
      selector:
        app: nginx
      ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 30080
      type: NodePort
    EOF
  delegate_to: "{{ groups['servers'][0] }}"

# 3. 배포 상태 확인 (디버깅용 로그 출력)
- name: Check Nginx Deployment status
  command: kubectl get pods -l app=nginx
  register: nginx_status
  delegate_to: "{{ groups['servers'][0] }}"

- name: Show Nginx Status
  debug:
    var: nginx_status.stdout_lines
