---
# 1. Helm 바이너리 설치
- name: Install Helm via script
  ansible.builtin.shell: |
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    chmod 700 get_helm.sh
    ./get_helm.sh
  args:
    creates: /usr/local/bin/helm
  become: true # /usr/local/bin에 설치하기 위해 root 권한 필요

# 2. Prometheus 커뮤니티 Helm 레포지토리 추가
- name: Add Prometheus community repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"
  become: true # k3s.yaml 접근 및 helm 설정을 위해 필요

# 3. 모니터링 네임스페이스 생성
- name: Create monitoring namespace
  kubernetes.core.k8s:
    name: "{{ monitoring_namespace }}"
    kind: Namespace
    state: present
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
  become: true # k3s.yaml 파일을 읽기 위해 필요

# 4. 통합 배포 (lookup을 사용하여 파일 내용 직접 주입)
- name: Deploy kube-prometheus-stack
  kubernetes.core.helm:
    name: "prometheus-stack"
    chart_ref: "prometheus-community/kube-prometheus-stack"
    chart_version: "{{ prometheus_chart_version }}"
    release_namespace: "{{ monitoring_namespace }}"
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    binary_path: /usr/local/bin/helm
    # [수정 포인트] 
    # 1. lookup('file', ...)을 사용하여 러너(Local)에 있는 파일을 읽습니다.
    # 2. combine()을 사용하여 파일 내용과 아래의 동적 values(Grafana IP 등)를 합칩니다.
    # admin 문제 recursive로 해결
    values: "{{ lookup('file', role_path + '/files/custom-values.yaml') | from_yaml | combine(dynamic_values, recursive=True) }}"
    wait: true
    timeout: "600s"
  become: true # k3s.yaml 읽기 및 Helm 실행 권한 획득
  vars:
    # 실시간으로 변하는 값들을 정의 (values 항목에서 파일 내용과 합쳐짐)
    dynamic_values:
      grafana:
        service:
          type: NodePort
          nodePort: 32000
        grafana.ini:
          server:
            root_url: "http://{{ ansible_host }}:32000"
